### PR TITLE
Add html support and switched ios(-moe) to OSS version.

### PR DESCRIPTION
**Pull request by fxzjshm**
Sorry, but I have not tested except Chrome.  
In your _gdx-dialogs-game_, (maybe) everything works well.

Oh, these commits are based on libgdx 1.9.5-SNAPSHOT.

### CODE REVIEW

**Comment by TomGrill** [comment]
I will review when 1.9.5 is released.

**Comment by fxzjshm** [comment]
libgdx 1.9.5 has been released, could you please review the code? I am going to update it this weekend. 
(You know I am in junior high now and have lots of homework, so I feel sorry for this. )

**Comment by TomGrill** [comment]
I hope I will find time after xmas.

**Comment by TomGrill** [comment]
Thank you!!

**Pull request merged**
