### PR TITLE
Android Build tools, booleans, optional thread hanging, documentation

### PR DESCRIPTION
**Pull request by samosaara**
- Updates android build tools. To the latest version (25.0.2).
- Adds optional, intentional, hanging of the main thread. For the desktop and android platforms, implemented with the use of polymorphism, everything before the change will keep working as before.
- Fixes bunch of pointless boolean checks. All commented why.
- Improvements to the documentation. Self-explanatory.

### CODE REVIEW

**Comment by TomGrill** [comment]
Hi thanks, can you give me an example when hanging might be a usefull option to use?

**Comment by samosaara** [comment]
First, as I said, I added it with polymorphism so not only it is optional it doesn't change anything, but now you can provide a boolean. 
Secondly I actually I wanted to implement that feature in  every platform. But I would need to ask for JS to do the command and wait for it to finish and I weren't going to use HTML so I was lazy but if do demand consistency it's OK. It can be done. I don't have a any apple product to test or know if the implementation of the IoS part hangs. But it's

**Comment by samosaara** [comment]
Bro. if you have a issue, tell me maybe i can fix it, if you dont like, it's ok my fork isn't going anywhere :neutral_face:

**Comment by TomGrill** [comment]
It is a busy week, did not have time to test and think through all the changes yet. I want to test the hang part first before deciding whether it should be part of the extension or just a users' implemention thing on their side.

**Comment by TomGrill** [comment]
So, I finallt got time to think about your PR. I thank you for the effort, you put in the PR, but I unfortunately I cannot accept it. 

I would love to take the cosmetic and documentation parts. 

I do not see the demand for the hang-feature and if somebody wants to implement a hanging thread the better solution would be to implement it in game code. Besides that in my opinion blocking the main thread is not a very good idea. Better solution would be to implement a pause feature for game which allows you to pause game progression. Pause updating (physics, etc.), keep rendering. With such an implementation you can pause certain systems in your game (time, movement, physics, ...) and keep others running (particle effects, rendering, ...). 
Besides that, you cannot longer react on input from the operating system like pause(), resume(), dispose() etc. which might happen in the mean time.

**Comment by samosaara** [comment]
Fair enough. Removed.

**Comment by TomGrill** [comment]
Please create a new PR with and only the cosmetic and doc changes if you like to. Cannot accept this version. Multiple small PRs are easier to review.

AndroidGDXProgressDialog.java is missing a while loop, which waits for Android to get things done.

**Comment by TomGrill** [comment]
Thanks for the PR. For this and other projects you might contribute in the future try to keep PRs small. Often it is better to create multiple small PRs than one big. Also you should disable all kind of auto-formating stuff in your IDE when changing code for a PR. It is always best to keep the files in the style they are. Everbody/project/IDE has a different view on how things should be formated. Makes code way easier to review when only relevant code is changed.

**Comment by samosaara** [comment]
Oh well fair enough sorry for any inconvenience I not even considered code formatting and I Also didn't stop to consider the size of the commit thanks for the tips and sorry again :grim:

**Comment by TomGrill** [comment]
All good :)

**Pull request merged**
